CATEGORIAS = [
    {
        "nome": "Papel",
        "descricao": "Papel sulfite, caderno, jornal, revista, cartolina, envelope, folheto, livro.",
        "instrucoes_descarte": "Descarte na coleta seletiva de papel, seco e sem contaminacao por gordura.",
        "cor_identificacao": "#B79A56",
        "reciclavel": True,
    },
    {
        "nome": "Papelão",
        "descricao": "Caixa de papelão, caixa de cereal, papelão de mudança.",
        "instrucoes_descarte": "Desmonte a caixa e descarte na coleta seletiva de papel - nao reciclavel se muito contaminado com gordura ou alimentos.",
        "cor_identificacao": "#B79A56",
        "reciclavel": True,
    },
    {
        "nome": "Plástico",
        "descricao": "Garrafa PET, potes, copos, sacolas, tampas, PVC, embalagens, brinquedos.",
        "instrucoes_descarte": "Descarte limpo e seco na coleta seletiva de plastico.",
        "cor_identificacao": "#52A37C",
        "reciclavel": True,
    },
    {
        "nome": "Vidro",
        "descricao": "Garrafas, potes, frascos.",
        "instrucoes_descarte": "Descarte na coleta seletiva de vidro - acondicione cacos quebrados com seguranca, embrulhados.",
        "cor_identificacao": "#2FA88C",
        "reciclavel": True,
    },
    {
        "nome": "Metal",
        "descricao": "Latas, aluminio, panelas, pregos, parafusos, ferragens, sucata.",
        "instrucoes_descarte": "Descarte na coleta seletiva de metal.",
        "cor_identificacao": "#7C93A6",
        "reciclavel": True,
    },
    {
        "nome": "Orgânico",
        "descricao": "Restos de comida, cascas, borra de cafe, ossos, folhas, galhos pequenos.",
        "instrucoes_descarte": "Descarte em composteira, se possivel, ou na coleta organica municipal.",
        "cor_identificacao": "#8AA34C",
        "reciclavel": False,
    },
    {
        "nome": "Rejeito",
        "descricao": "Papel higienico usado, guardanapo contaminado, fralda, absorvente, esponja.",
        "instrucoes_descarte": "Sem aproveitamento na coleta seletiva comum - descarte no lixo comum.",
        "cor_identificacao": "#9A9A8F",
        "reciclavel": False,
    },
    {
        "nome": "Eletrônico",
        "descricao": "Celular, computador, TV, cabos, carregadores, controles, consoles.",
        "instrucoes_descarte": "Nunca na coleta reciclavel comum - leve a um ponto de coleta de e-lixo.",
        "cor_identificacao": "#8B72C9",
        "reciclavel": False,
    },
    {
        "nome": "Pilha ou bateria",
        "descricao": "Pilhas e baterias de qualquer tipo.",
        "instrucoes_descarte": "Nunca no lixo comum ou reciclavel - leve a um ponto de coleta especifico (muitos supermercados aceitam).",
        "cor_identificacao": "#D9534F",
        "reciclavel": False,
    },
    {
        "nome": "Lâmpada",
        "descricao": "LED, fluorescente, incandescente.",
        "instrucoes_descarte": "Leve a um ponto de coleta apropriado - lampadas fluorescentes contem mercurio.",
        "cor_identificacao": "#E0B84B",
        "reciclavel": False,
    },
    {
        "nome": "Resíduo de saúde",
        "descricao": "Seringas, agulhas, medicamentos vencidos, curativos.",
        "instrucoes_descarte": "Leve a uma farmacia ou unidade de saude com coleta apropriada.",
        "cor_identificacao": "#D9578E",
        "reciclavel": False,
    },
    {
        "nome": "Óleo de cozinha",
        "descricao": "Oleo de fritura usado.",
        "instrucoes_descarte": "Nunca jogue na pia ou vaso sanitario - armazene em recipiente fechado e leve a um ponto de coleta.",
        "cor_identificacao": "#A9793C",
        "reciclavel": False,
    },
    {
        "nome": "Resíduo perigoso",
        "descricao": "Tinta, solvente, produtos quimicos concentrados, inseticidas, inflamaveis.",
        "instrucoes_descarte": "Nao e reciclavel comum - siga a orientacao especifica do fabricante ou de um ponto de coleta especializado.",
        "cor_identificacao": "#E08A2B",
        "reciclavel": False,
    },
    {
        "nome": "Volumoso",
        "descricao": "Moveis, colchao, sofa, eletrodomesticos grandes.",
        "instrucoes_descarte": "Acione a coleta de volumosos, um ecoponto ou servico municipal especifico.",
        "cor_identificacao": "#8A80B0",
        "reciclavel": False,
    },
    {
        "nome": "Têxtil",
        "descricao": "Roupas, calcados, tecidos, toalhas, lencois.",
        "instrucoes_descarte": "Se em bom estado, prefira doar - senao, leve a um ponto de coleta textil.",
        "cor_identificacao": "#5C93A6",
        "reciclavel": False,
    },
    {
        "nome": "Outro",
        "descricao": "Quando nenhuma categoria acima se aplica claramente.",
        "instrucoes_descarte": "Descricao insuficiente para orientar o descarte - detalhe material, formato ou uso do objeto.",
        "cor_identificacao": "#9A9A8F",
        "reciclavel": False,
    },
]
